import { cn } from '@/src/lib/utils'
import type { Metadata } from 'next'
import { Cormorant_Garamond, Montserrat } from 'next/font/google'
import './globals.css'

const cormorant = Cormorant_Garamond({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-family-title',
})

const montserrat = Montserrat({
	subsets: ['latin'],
	variable: '--font-family-text',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='fr'>
			<body
				className={cn(
					montserrat.variable,
					cormorant.variable,
					'antialiased',
				)}
			>
				{children}
			</body>
		</html>
	)
}
